---
name: tests
on:
  push:
    branches:
      - master
      - '*.*.*'
    paths-ignore:
      - '**.rst'
  pull_request:
    branches:
      - master
      - '*.*.*'
    paths-ignore:
      - '**.rst'
jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.10'
          - '3.9'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: poetry install
      - run: poetry run pytest
